### PR TITLE
add mechansim to ensure that the QUDA MG setup is reset regularly

### PR DESCRIPTION
**Pull request by kostrzewa**
to be set via the MGResetSetupThreshold parameter in the QUDA ExternalInverter section

This nf=4 twisted mass run (roughly at maximal twist) works rather nicely with this setup.

```
L=16
T=32
Measurements = 1000
#StartCondition = hot
StartCondition = continue
InitialStoreCounter = readin
2KappaMu = 0.002
kappa = 0.163255
NSave = 500000
ThetaT = 1.0
UseEvenOdd = yes
ReversibilityCheck = no
ReversibilityCheckIntervall = 100
DebugLevel = 3
ompnumthreads = 6

StrictResidualCheck = yes

BeginExternalInverter QUDA
  Pipeline = 10
  gcrNkrylov = 20
  MGCoarseMuFactor = 1.0, 1.0, 20.0
  MGNumberOfLevels = 3
  MGNumberOfVectors = 24, 24, 24
  MGSetupSolver = cg
  MGSetup2KappaMu = 0.002
  MGVerbosity = summarize, summarize, summarize
  MGVerbosity = silent, silent, silent
  MGSetupSolverTolerance = 5e-7, 5e-7, 5e-7
  MGSetupMaxSolverIterations = 1500, 1500, 1500
  MGCoarseSolverType = gcr, gcr, cagcr
  MgCoarseSolverTolerance = 0.2, 0.2, 0.2
  MGCoarseMaxSolverIterations = 10, 10, 10
  MGSmootherType = cagcr, cagcr, cagcr
  MGSmootherTolerance = 0.1, 0.1, 0.1
  MGSmootherPreIterations = 0, 0, 0
  MGSmootherPostIterations = 4, 4, 4
  MGBlockSizesX = 4,2
  MGBlockSizesY = 4,2
  MGBlockSizesZ = 4,2
  MGBlockSizesT = 4,2
  MGOverUnderRelaxationFactor = 0.90, 0.90, 0.90
  # when the step in the gauge field is too large, we have to rerun the setup
  # for the solver to not break down
  # here we specify the maximum step size for which we attempt an update instead
  # of a reset
  MGResetSetupThreshold = 0.201
EndExternalInverter

# note by BaKo: 
#   online measurements currently lead to residual violations
#   which are currently unclear to me
#
# BeginMeasurement CORRELATORS
#   Frequency = 1
# EndMeasurement

BeginMonomial GAUGE
  Type = Iwasaki
  beta = 1.90
  Timescale = 0
EndMonomial

BeginMonomial DET
  Timescale = 1
  2KappaMu = 0.2
  kappa = 0.163255
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 500
  Name = det_d1
  UseExternalInverter = QUDA
  solver = cg
  usesloppyprecision = half
EndMonomial

BeginMonomial DET
  Timescale = 1
  2KappaMu = 0.2
  kappa = 0.163255
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 500
  Name = det_d2
  UseExternalInverter = QUDA
  solver = cg
  usesloppyprecision = half
EndMonomial

BeginMonomial DETRATIO
  Timescale = 2
  2KappaMu = 0.02
  kappa = 0.163255
  2KappaMu2 = 0.2
  kappa2 = 0.163255
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 2000
  Name = detratio1_d1
  UseExternalInverter = QUDA
  solver = cg
  usesloppyprecision = half
EndMonomial

BeginMonomial DETRATIO
  Timescale = 2
  2KappaMu = 0.02
  kappa = 0.163255
  2KappaMu2 = 0.2
  kappa2 = 0.163255
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 2000
  Name = detratio1_d2
  UseExternalInverter = QUDA
  solver = cg
  usesloppyprecision = half
EndMonomial

BeginMonomial DETRATIO
  Timescale = 3
  2KappaMu = 0.002
  kappa = 0.163255
  2KappaMu2 = 0.02
  kappa2 = 0.163255
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 10000
  Name = detratio2_d1
  UseExternalInverter = QUDA
  Solver = mg
  UseSloppyPrecision = single
EndMonomial

BeginMonomial DETRATIO
  Timescale = 3
  2KappaMu = 0.002
  kappa = 0.163255
  2KappaMu2 = 0.02
  kappa2 = 0.163255
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 10000
  Name = detratio2_d2
  UseExternalInverter = QUDA
  Solver = mg
  UseSloppyPrecision = single
EndMonomial

BeginIntegrator 
  Type0 = 2MN
  Type1 = 2MN
  Type2 = 2MN
  Type3 = 2MN
  IntegrationSteps0 = 1
  IntegrationSteps1 = 1
  IntegrationSteps2 = 1 
  IntegrationSteps3 = 10
  Tau = 1.0
  Lambda0 = 0.19
  Lambda1 = 0.20
  Lambda2 = 0.205
  Lambda3 = 0.210
  NumberOfTimescales = 4
EndIntegrator
```

### CODE REVIEW

**Comment by kostrzewa** [comment]
By the way: about 650 seconds / trajectory using my measly GTX 1060 :)

**Comment by kostrzewa** [comment]
A better solution would be to do something like this: https://github.com/JeffersonLab/chroma/blob/8af1b2d48836724ca2601dbb0c8428c1dc190737/lib/actions/ferm/invert/quda_solvers/syssolver_mdagm_clover_quda_multigrid_w.h#L681

That way, one would not have to guess a good value for `MGResetSetupThreshold`.

**Comment by Marcogarofalo** [comment]
with the infile at the top of this page I get an error at the monomial detratio2_d1
```
# TM_QUDA: Performing MG Preconditioner Setup for gauge 0.000000
# TM_QUDA: Generating MG Setup with mu = 0.006125386665 instead of 0.061253866650
# QUDA: Tuned block=(192,1,1), grid=(86,1,8), shared_bytes=0, aux=(8,2,0,0) giving 0.00 Gflop/s, 818.53 GB/s for N4quda9CopyGaugeINS_12CopyGaugeArgIfdLi18ENS_5gauge11FloatNOrderIfLi18ELi2ELi18EL20QudaStaggeredPhase_s0ELb1EL19QudaGhostExchange_sn2147483648ELb0EEENS3_IdLi18ELi2ELi18ELS4_0ELb1ELS5_n2147483648ELb0EEEEEEE with GPU-offline,vol=32768,stride=18432,precision=8,geometry=4,Nc=3vol=32768,stride=18432,precision=4,geometry=4,Nc=3
# QUDA: Tuned block=(32,1,1), grid=(64,1,8), shared_bytes=0, aux=(8,2,0,0) giving 0.00 Gflop/s, 405.00 GB/s for N4quda9CopyGaugeINS_12CopyGaugeArgIfdLi18ENS_5gauge11FloatNOrderIfLi18ELi2ELi18EL20QudaStaggeredPhase_s0ELb1EL19QudaGhostExchange_sn2147483648ELb0EEENS3_IdLi18ELi2ELi18ELS4_0ELb1ELS5_n2147483648ELb0EEEEEEE with GPU-offline,vol=32768,stride=18432,precision=8,geometry=4,Nc=3vol=32768,stride=18432,precision=4,geometry=4,Nc=3,ghost
MG level 1 (GPU): ERROR: add_coarse_tm not enabled for non-wilson coarsenings (rank 0, host r246n14, coarse_op.cuh:427 in Launch())
MG level 1 (GPU):        last kernel called was (name=N4quda10CalculateYILb1EL19QudaFieldLocation_s2ENS_13CalculateYArgILb1EfLi2ELi2ELi24ELi24ENS_5gauge10FieldOrderIfLi48ELi2EL21QudaGaugeFieldOrder_s13ELb1EsEENS4_IfLi48ELi2ELS5_13ELb1EiEES6_NS_11colorspinor12FieldOrderCBIfLi2ELi24ELi24EL16QudaFieldOrder_s9EssLb0ELb0EEENS9_IfLi4ELi24ELi24ELSA_9EssLb0ELb0EEESB_S6_EEEE,volume=2x2x2x2,aux=GPU-offline,vol=256,stride=128,precision=2,order=9,Ns=2,Nc=576,TwistFlavour=1,comm=0001,computeCoarseTmDiagonal,GPU-device)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
```

**Comment by kostrzewa** [comment]
3-level MG does not work with QUDA's GK branch right now. We have a bit of a catch-22: we don't get twisted clover mass precon and 1+1 non-deg twisted clover & 3-level MG at the same time right now.

Using QUDA 1.1.x and disabling the setting of `tm_rho` will work for 2+(1+1) twisted mass HMC, however.

We should probably wrap the setting of `tm_rho` in the TM_QUDA_EXPERIMENTAL macro to make it compatible with QUDA 1.1.x.

**Pull request merged**
