### PR TITLE
Interface with new 'tm_rho' parameter for the preconditioned twisted …

### PR DESCRIPTION
**Pull request by kostrzewa**
…clover operator to support tmLQCD-style mass-preconditioning in the HMC using QUDA solvers. This breaks compatibility with QUDA versions which do not have this parameter yet.

Requires the QUDA version in https://github.com/qcdcode/quda/pull/15

### CODE REVIEW

**Comment by kostrzewa** [comment]
With this, we can reproduce our nf=2 twisted clover and nf=4 twisted clover renormalisation runs.

Next step is to get the MG to work also for twisted clover including the rho parameter.

```
L=16
T=32

Measurements = 1000
StartCondition = continue
InitialStoreCounter = readin
2KappaMu = 0.002471220000
kappa = 0.13729
csw = 1.57551

NSave = 500000
ThetaT = 1.0
UseEvenOdd = yes
ReversibilityCheck = no
ReversibilityCheckIntervall = 100
DebugLevel = 1
ompnumthreads = 6

StrictResidualCheck = yes

BeginMonomial GAUGE
  Type = Iwasaki
  beta = 2.10
  Timescale = 0
EndMonomial

BeginMonomial CLOVERDET
  Timescale = 1
  2KappaMu = 0.002471220000
  rho = 0.2
  csw = 1.57551
  kappa = 0.13729
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 1000
  Name = det_d1
  UseExternalInverter = QUDA
  solver = cg
  usesloppyprecision = half
EndMonomial

BeginMonomial CLOVERDETRATIO
  Timescale = 2
  2KappaMu = 0.002471220000
  csw = 1.57551
  rho = 0.02
  rho2 = 0.2
  kappa = 0.13729
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 5000
  Name = detratio1_d1
  UseExternalInverter = QUDA
  solver = cg
  usesloppyprecision = half
EndMonomial

BeginMonomial CLOVERDETRATIO
  Timescale = 3
  2KappaMu = 0.002471220000
  rho = 0.0
  rho2 = 0.02
  kappa = 0.13729
  csw = 1.57551
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-15
  MaxSolverIterations = 10000
  Name = detratio2_d1
  UseExternalInverter = QUDA
  solver = cg
  usesloppyprecision = half
EndMonomial

BeginIntegrator 
  Type0 = 2MNFG
  Type1 = 2MNFG
  Type2 = 2MNFG
  Type3 = 2MNFG
  IntegrationSteps0 = 1
  IntegrationSteps1 = 1
  IntegrationSteps2 = 1 
  IntegrationSteps3 = 12
  Tau = 1.0
  Lambda0 = 0.19
  Lambda1 = 0.20
  Lambda2 = 0.205
  Lambda3 = 0.210
  NumberOfTimescales = 4
EndIntegrator
```

**Comment by kostrzewa** [comment]
There are of course major CPU overheads in this as the clover term and its inverse are calculated quite often for the CPU operators.

**Comment by sunpho84** [comment]
mhhh why is this inducing CPU overhead? this is just wiring the parameters to the input file, right?

**Comment by kostrzewa** [comment]
> mhhh why is this inducing CPU overhead? this is just wiring the parameters to the input file, right?

we need to apply `Qsw_plus_psi` and `Qsw_minus_psi` in a bunch of places

**Comment by kostrzewa** [comment]
I meant "compared to twisted mass without a clover term", this has a different balance because we compute the clover term and its inverse in addition to the CPU parts that the clover and non-clover HMC share.

**Comment by sunpho84** [comment]
ok for the sake of my understanding, they had to be applied even without tm_rho, right? so the overhead is unrelated to it I guess

**Comment by kostrzewa** [comment]
> ok for the sake of my understanding, they had to be applied even without tm_rho, right? so the overhead is unrelated to it I guess

yes, should have formulated that more clearly

**Pull request merged**
