### PR TITLE
synch up with quda_work and quda_work_add_actions branches

### PR DESCRIPTION
**Pull request by kostrzewa**

### CODE REVIEW

**Comment by Marcogarofalo** [comment]
I am a bit confused, I tried to compare `M_quda` and `print_spinor_similar_components` on the same source 
```
assign(tempE[1], tempE[0], VOLUMEPLUSRAND/2);
M_quda(P, tempE[0]); // quda changes the source
mul_gamma5(P, VOLUME/2);
Qtm_plus_psi(temp[0], tempE[1]);
print_spinor_similar_components(temp[0], P, VOLUME/2, 1e-4);
```
but I get
```
0 out of 128 match
```
shouldn't be the same?

**Comment by kostrzewa** [comment]
Works for me, but only for twisted mass, not for twisted clover. I have introduced a segfault however.

**Comment by kostrzewa** [comment]
```
ix: 126 iy: 126 s3.c1: [Q,P]:(0.167312,0.226511)(0.167312,0.226511)
ix: 126 iy: 126 s3.c2: [Q,P]:(-0.334979,0.139255)(-0.334979,0.139255)
ix: 127 iy: 127 s0.c0: [Q,P]:(1.061326,-0.087211)(1.061326,-0.087211)
ix: 127 iy: 127 s0.c1: [Q,P]:(1.061326,-0.087211)(1.061326,-0.087211)
ix: 127 iy: 127 s0.c2: [Q,P]:(1.061326,-0.087211)(1.061326,-0.087211)
ix: 127 iy: 127 s1.c0: [Q,P]:(0.456381,-0.026932)(0.456381,-0.026932)
ix: 127 iy: 127 s1.c1: [Q,P]:(0.634066,-0.149004)(0.634066,-0.149004)
ix: 127 iy: 127 s1.c2: [Q,P]:(-0.093528,0.404367)(-0.093528,0.404367)
ix: 127 iy: 127 s2.c0: [Q,P]:(-0.392306,0.244273)(-0.392306,0.244273)
ix: 127 iy: 127 s2.c1: [Q,P]:(0.065892,0.488863)(0.065892,0.488863)
ix: 127 iy: 127 s2.c2: [Q,P]:(0.350091,-0.417890)(0.350091,-0.417890)
ix: 127 iy: 127 s3.c0: [Q,P]:(-1.094931,0.428306)(-1.094931,0.428306)
ix: 127 iy: 127 s3.c1: [Q,P]:(-0.695281,0.352196)(-0.695281,0.352196)
ix: 127 iy: 127 s3.c2: [Q,P]:(0.138426,-0.227172)(0.138426,-0.227172)
128 out of 128 match
```

**Comment by kostrzewa** [comment]
> I am a bit confused, I tried to compare `M_quda` and `print_spinor_similar_components` on the same source
> 
> ```
> assign(tempE[1], tempE[0], VOLUMEPLUSRAND/2);
> M_quda(P, tempE[0]); // quda changes the source
> mul_gamma5(P, VOLUME/2);
> Qtm_plus_psi(temp[0], tempE[1]);
> print_spinor_similar_components(temp[0], P, VOLUME/2, 1e-4);
> ```
> 
> but I get
> 
> ```
> 0 out of 128 match
> ```
> 
> shouldn't be the same?

Could you explain a bit more (at some point) what you tested here? Was it for the twisted-clover operator?

**Comment by Marcogarofalo** [comment]
I think I am using the TMWILSON operator, the input file is sample-hmc0-input with the change in the DET monomial to use quda inverter:
```
BeginMonomial DET
  Timescale = 1
  2KappaMu = 0.177
  kappa = 0.177
  AcceptancePrecision =  1e-20
  ForcePrecision = 1e-12
  Name = det
  #Solver = CG
  useexternalinverter = quda
  usesloppyprecision = single
  usecompression = 12
EndMonomial
```

**Comment by kostrzewa** [comment]
the problem is the compression

**Comment by kostrzewa** [comment]
the phases of the twisted boundary conditions are lost in the compression. For QPhiX, Martin and I added operators with phases to support compression, in QUDA, this is currently not yet possible (it could be done, however, since there's a 13-parameter gauge compression available for staggered quarks)

**Comment by Marcogarofalo** [comment]
commenting out usecompression I get `128 out of 128 match` thank you.

**Comment by kostrzewa** [comment]
thanks for confirming

**Pull request merged**
